/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dorset/files/help': RouteRecordInfo<
      '/dorset/files/help',
      '/dorset/files/help',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dorset/forum/main': RouteRecordInfo<
      '/dorset/forum/main',
      '/dorset/forum/main',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dorset/main': RouteRecordInfo<
      '/dorset/main',
      '/dorset/main',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dorset/profiles/jay': RouteRecordInfo<
      '/dorset/profiles/jay',
      '/dorset/profiles/jay',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/intrazone/main': RouteRecordInfo<
      '/intrazone/main',
      '/intrazone/main',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/intrazone/sites/manifesto': RouteRecordInfo<
      '/intrazone/sites/manifesto',
      '/intrazone/sites/manifesto',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/intrazone/sites/r1d3r/2012': RouteRecordInfo<
      '/intrazone/sites/r1d3r/2012',
      '/intrazone/sites/r1d3r/2012',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/intrazone/sites/r1d3r/boxelf': RouteRecordInfo<
      '/intrazone/sites/r1d3r/boxelf',
      '/intrazone/sites/r1d3r/boxelf',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/intrazone/sites/r1d3r/main': RouteRecordInfo<
      '/intrazone/sites/r1d3r/main',
      '/intrazone/sites/r1d3r/main',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/myself/chest': RouteRecordInfo<
      '/myself/chest',
      '/myself/chest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/myself/demoEnd': RouteRecordInfo<
      '/myself/demoEnd',
      '/myself/demoEnd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/myself/options': RouteRecordInfo<
      '/myself/options',
      '/myself/options',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dorset/files/help.vue': {
      routes:
        | '/dorset/files/help'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dorset/forum/main.vue': {
      routes:
        | '/dorset/forum/main'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dorset/main.vue': {
      routes:
        | '/dorset/main'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dorset/profiles/jay.vue': {
      routes:
        | '/dorset/profiles/jay'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/intrazone/main.vue': {
      routes:
        | '/intrazone/main'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/intrazone/sites/manifesto.vue': {
      routes:
        | '/intrazone/sites/manifesto'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/intrazone/sites/r1d3r/2012.vue': {
      routes:
        | '/intrazone/sites/r1d3r/2012'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/intrazone/sites/r1d3r/boxelf.vue': {
      routes:
        | '/intrazone/sites/r1d3r/boxelf'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/intrazone/sites/r1d3r/main.vue': {
      routes:
        | '/intrazone/sites/r1d3r/main'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/myself/chest.vue': {
      routes:
        | '/myself/chest'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/myself/demoEnd.vue': {
      routes:
        | '/myself/demoEnd'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/myself/options.vue': {
      routes:
        | '/myself/options'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
